version: '2'
services:
  api:
    build: .
    container_name: api
    command: bash -c "cd /src/rest && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - mongo
    volumes:
      - ./src:/src
      - ./tmp:/tmp

  app:
    build: .
    container_name: app
    command: bash -c "cd /src/app && yarn install --network-timeout 300000 && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ./src:/src
      - node_modules:/src/app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true

  mongo:
    build: .
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    command: /usr/bin/mongod --bind_ip 0.0.0.0

volumes:
  node_modules:

    